// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLrEFGYKWapJPDq250DGAJtkl8bt-6nYM',
    appId: '1:564952407240:web:fc50c90b270f22818d59fd',
    messagingSenderId: '564952407240',
    projectId: 'mobile-real-estate',
    authDomain: 'mobile-real-estate.firebaseapp.com',
    storageBucket: 'mobile-real-estate.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGEianaf8eK0EMgbRAcWzLtNCA8LP3Nag',
    appId: '1:564952407240:android:be08aa2e5b82aa778d59fd',
    messagingSenderId: '564952407240',
    projectId: 'mobile-real-estate',
    storageBucket: 'mobile-real-estate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCThkF5IvNx6c8vzHWCgfaarufA_7a6A-U',
    appId: '1:564952407240:ios:81946634b296949c8d59fd',
    messagingSenderId: '564952407240',
    projectId: 'mobile-real-estate',
    storageBucket: 'mobile-real-estate.firebasestorage.app',
    iosClientId: '564952407240-rdv2po8g01qt9n5gktfk5eg2de9eljl5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCThkF5IvNx6c8vzHWCgfaarufA_7a6A-U',
    appId: '1:564952407240:ios:81946634b296949c8d59fd',
    messagingSenderId: '564952407240',
    projectId: 'mobile-real-estate',
    storageBucket: 'mobile-real-estate.firebasestorage.app',
    iosClientId: '564952407240-rdv2po8g01qt9n5gktfk5eg2de9eljl5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLrEFGYKWapJPDq250DGAJtkl8bt-6nYM',
    appId: '1:564952407240:web:714d3b1f3ea744b28d59fd',
    messagingSenderId: '564952407240',
    projectId: 'mobile-real-estate',
    authDomain: 'mobile-real-estate.firebaseapp.com',
    storageBucket: 'mobile-real-estate.firebasestorage.app',
  );
}
